export default function designHome(){
    const mymaindiv=document.createElement('div');
    mymaindiv.classList.add('remove');
    const h1=document.createElement('h1');
    h1.textContent='Muturi restaurant and bar';
    const explainerdiv=document.createElement('div');
    explainerdiv.classList.add('explainerdiv');
    const explainer=document.createElement('p');
    explainer.classList.add('explainerp');
    explainer.textContent='In this restaurant we offer the best experience in fine dining.The aura is great for your special occassions.We offer the best foods and also drinks of the best quality.Bottles of wine wich have been aged for the best tasting wine.Visit us to have great moments you will never forget.';
    explainerdiv.appendChild(h1);
    explainerdiv.appendChild(explainer);
    mymaindiv.appendChild(explainerdiv);
    const authorspan=document.createElement('span');
    authorspan.textContent='Chef Denis';
    authorspan.classList.add('authorname');
    explainer.appendChild(authorspan);
    const hoursdiv=createHoursdiv();
    mymaindiv.appendChild(hoursdiv);
    const locationDiv=document.createElement('div');
    locationDiv.classList.add('locationdiv');
    const h2Location=document.createElement('h2');
    h2Location.textContent='Location';
    locationDiv.appendChild(h2Location);
    const locationspan=document.createElement('span');
    locationspan.textContent='123 kenyatta avenue,Ngong hills,Maine';
    locationDiv.appendChild(locationspan);
    mymaindiv.appendChild(locationDiv);
    return mymaindiv;
}
function createHoursdiv(){
    const hoursdiv=document.createElement('div');
    hoursdiv.classList.add('hoursdiv');
    const hoursh2=document.createElement('h2');
    hoursh2.textContent='Hours';
    const timespan=document.createElement('span');
    timespan.textContent='Sunday:8am-8pm';
    const timespan1=document.createElement('span');
    timespan1.textContent='Monday:6am-6pm';
    const timespan2=document.createElement('span');
    timespan2.textContent='Tuesday:6am-8pm';
    const timespan3=document.createElement('span');
    timespan3.textContent='Wednesday:8am-8pm';
    const timespan4=document.createElement('span');
    timespan4.textContent='Thursday:8am-8pm';
    const timespan5=document.createElement('span');
    timespan5.textContent='Friday:8am-8pm';
    const timespan6=document.createElement('span');
    timespan6.textContent='Saturday:8am-8pm';
    hoursdiv.appendChild(hoursh2);
    hoursdiv.appendChild(timespan);
    hoursdiv.appendChild(timespan1);
    hoursdiv.appendChild(timespan2);
    hoursdiv.appendChild(timespan3);
    hoursdiv.appendChild(timespan4);
    hoursdiv.appendChild(timespan5);
    hoursdiv.appendChild(timespan6);
    return hoursdiv;
}